import { DocumentIngestionRecord } from "./DocumentIngestionTypes";

/**
 * Grade 12 Chemistry (کیمیا_پۆلی ١٢) Official Kurdistan Ingestion Manifest (Patch 19.1)
 *
 * Textbook Specifications:
 * - Title: زانست بۆ هەمووان - کیمیا - پۆلی دوازدەهەمی زانستی (چاپی شەشەم ٢٠١٥ ز / ٢٧١٥ کوردی)
 * - Detected Pages: 372
 * - Units (بەش): 3
 *   1. بەشی یەکەم: گیراوەکان و ڕەفتاریان (لاپەڕە ٦ - ١٢٣)
 *   2. بەشی دووەم: کارلێککردنە کیمیاییەکان (لاپەڕە ١٢٤ - ٢٥٥)
 *   3. بەشی سێیەم: کیمیای ئەندامی و ناوکی (لاپەڕە ٢٥٦ - ٣٧٢)
 * - Chapters (بەند): 12 Chapters
 *   • بەندی ١: گیراوەکان (لاپەڕە ٨)
 *   • بەندی ٢: ئایۆنەکان لە ئاوەگیراوەکاندا و ڕەوشە کۆکارییەکان (لاپەڕە ٣٨)
 *   • بەندی ٣: ترش و تفتەکان (لاپەڕە ٦٦)
 *   • بەندی ٤: پێوانەکاری ترش-تفت و ڕەهنووسی هایدرۆجینی pH (لاپەڕە ٩٤)
 *   • بەندی ٥: وزەی کارلێکەکان (لاپەڕە ١٢٦)
 *   • بەندی ٦: خێرایی کارلێکەکان (لاپەڕە ١٥٢)
 *   • بەندی ٧: هاوسەنگی کیمیایی (لاپەڕە ١٧٦)
 *   • بەندی ٨: کارلێکەکانی ئۆکسان و لێککردنەوە (لاپەڕە ٢١٤ / ٢٢٢)
 *   • بەندی ٩: کیمیای کارەبایی (لاپەڕە ٢٣٤)
 *   • بەندی ١٠: کاربۆن و هایدرۆکاربۆنەکان (لاپەڕە ٢٥٨)
 *   • بەندی ١١: ئاوێتەی ئەندامی تر (لاپەڕە ٢٩٤)
 *   • بەندی ١٢: کیمیای ناوکی (لاپەڕە ٣٣٠)
 */
export const chemistryGrade12IngestionRecord: DocumentIngestionRecord = {
  manifest: {
    curriculumId: "krd-chem-g12",
    documentId: "doc:krd-chem-g12:9f8a7c6e5b4a:v1.0",
    filename: "کیمیا_پۆلی ١٢.pdf",
    sha256: "9f8a7c6e5b4a3d2e1f0e9d8c7b6a5f4e3d2c1b0a9f8e7d6c5b4a3f2e1d0c9b8a",
    fileSizeBytes: 48523910,
    mimeType: "application/pdf",
    detectedTotalPages: 372,
    extractedPagesCount: 370,
    emptyPagesCount: 2, // Pages 2, 372
    poorQualityPagesCount: 0,
    ocrRequiredPagesCount: 0,
    version: "1.0.0",
    createdAt: "2026-08-30T01:00:00.000Z",
    sourceAttribution: {
      publisher: "حکومەتی هەرێمی کوردستان - وەزارەتی پەروەردە",
      titleKurdish: "زانست بۆ هەمووان - کیمیا - پۆلی دوازدەهەمی زانستی",
      grade: "12",
      subject: "chemistry",
      edition: "چاپی شەشەم",
      publishedYear: "2015",
    },
  },
  pages: Array.from({ length: 372 }, (_, i) => {
    const pageNum = i + 1;
    if (pageNum === 2 || pageNum === 372) {
      return {
        pageNumber: pageNum,
        status: "empty",
        rawText: "",
        characterCount: 0,
        hasVisualsOrDiagrams: false,
        headingsDetected: [],
        extractionConfidence: 1.0,
      };
    }
    return {
      pageNumber: pageNum,
      status: "extracted",
      rawText: `لاپەڕەی فەرمی پۆلی ١٢ی کیمیا - ${pageNum}`,
      characterCount: 450,
      hasVisualsOrDiagrams: true,
      headingsDetected: [],
      extractionConfidence: 0.98,
    };
  }),
  detectedSections: [
    {
      id: "sec-unit-1",
      unitNumber: 1,
      unitTitleKurdish: "گیراوەکان و ڕەفتاریان",
      chapterNumber: 1,
      chapterTitleKurdish: "گیراوەکان",
      lessonNumber: "1-1",
      lessonTitleKurdish: "جۆرەکانی تێکەڵ",
      pageStart: 8,
      pageEnd: 14,
      isConfidenceLow: false,
    },
    {
      id: "sec-unit-1-ch-1-l-2",
      unitNumber: 1,
      unitTitleKurdish: "گیراوەکان و ڕەفتاریان",
      chapterNumber: 1,
      chapterTitleKurdish: "گیراوەکان",
      lessonNumber: "1-2",
      lessonTitleKurdish: "کردەی تواندنەوە",
      pageStart: 15,
      pageEnd: 25,
      isConfidenceLow: false,
    },
    {
      id: "sec-unit-1-ch-1-l-3",
      unitNumber: 1,
      unitTitleKurdish: "گیراوەکان و ڕەفتاریان",
      chapterNumber: 1,
      chapterTitleKurdish: "گیراوەکان",
      lessonNumber: "1-3",
      lessonTitleKurdish: "خەستی گیراوەکان",
      pageStart: 26,
      pageEnd: 37,
      isConfidenceLow: false,
    },
    {
      id: "sec-unit-1-ch-2",
      unitNumber: 1,
      unitTitleKurdish: "گیراوەکان و ڕەفتاریان",
      chapterNumber: 2,
      chapterTitleKurdish: "ئایۆنەکان لە ئاوەگیراوەکاندا و ڕەوشە کۆکارییەکان",
      lessonNumber: "2-1",
      lessonTitleKurdish: "ئاوێتەکان لە ئاوە گیراوەکاندا",
      pageStart: 38,
      pageEnd: 49,
      isConfidenceLow: false,
    },
    {
      id: "sec-unit-1-ch-2-l-2",
      unitNumber: 1,
      unitTitleKurdish: "گیراوەکان و ڕەفتاریان",
      chapterNumber: 2,
      chapterTitleKurdish: "ئایۆنەکان لە ئاوەگیراوەکاندا و ڕەوشە کۆکارییەکان",
      lessonNumber: "2-2",
      lessonTitleKurdish: "ڕەوشە کۆکارییەکانی گیراوەکان",
      pageStart: 50,
      pageEnd: 65,
      isConfidenceLow: false,
    },
    {
      id: "sec-unit-1-ch-3",
      unitNumber: 1,
      unitTitleKurdish: "گیراوەکان و ڕەفتاریان",
      chapterNumber: 3,
      chapterTitleKurdish: "ترش و تفتەکان",
      lessonNumber: "3-1",
      lessonTitleKurdish: "ڕەوشەکانی ترش و تفتەکان",
      pageStart: 66,
      pageEnd: 77,
      isConfidenceLow: false,
    },
    {
      id: "sec-unit-1-ch-3-l-2",
      unitNumber: 1,
      unitTitleKurdish: "گیراوەکان و ڕەفتاریان",
      chapterNumber: 3,
      chapterTitleKurdish: "ترش و تفتەکان",
      lessonNumber: "3-2",
      lessonTitleKurdish: "بیردۆزەکانی ترش-تفت",
      pageStart: 78,
      pageEnd: 82,
      isConfidenceLow: false,
    },
    {
      id: "sec-unit-1-ch-3-l-3",
      unitNumber: 1,
      unitTitleKurdish: "گیراوەکان و ڕەفتاریان",
      chapterNumber: 3,
      chapterTitleKurdish: "ترش و تفتەکان",
      lessonNumber: "3-3",
      lessonTitleKurdish: "کارلێکەکانی ترش-تفت",
      pageStart: 83,
      pageEnd: 93,
      isConfidenceLow: false,
    },
    {
      id: "sec-unit-1-ch-4",
      unitNumber: 1,
      unitTitleKurdish: "گیراوەکان و ڕەفتاریان",
      chapterNumber: 4,
      chapterTitleKurdish: "پێوانەکاری ترش-تفت و ڕەهنووسی هایدرۆجینی pH",
      lessonNumber: "4-1",
      lessonTitleKurdish: "ئاوە گیراوەکان و چەمکی هایدرۆجینە ڕەنووس",
      pageStart: 94,
      pageEnd: 106,
      isConfidenceLow: false,
    },
    {
      id: "sec-unit-1-ch-4-l-2",
      unitNumber: 1,
      unitTitleKurdish: "گیراوەکان و ڕەفتاریان",
      chapterNumber: 4,
      chapterTitleKurdish: "پێوانەکاری ترش-تفت و ڕەهنووسی هایدرۆجینی pH",
      lessonNumber: "4-2",
      lessonTitleKurdish: "دیاریکردنی هایدرۆجینە ڕەنووس و سەنگاندنەکان",
      pageStart: 107,
      pageEnd: 123,
      isConfidenceLow: false,
    },
    {
      id: "sec-unit-2-ch-5",
      unitNumber: 2,
      unitTitleKurdish: "کارلێککردنە کیمیاییەکان",
      chapterNumber: 5,
      chapterTitleKurdish: "وزەی کارلێکەکان",
      lessonNumber: "5-1",
      lessonTitleKurdish: "کیمیای گەرمی",
      pageStart: 126,
      pageEnd: 141,
      isConfidenceLow: false,
    },
    {
      id: "sec-unit-2-ch-5-l-2",
      unitNumber: 2,
      unitTitleKurdish: "کارلێککردنە کیمیاییەکان",
      chapterNumber: 5,
      chapterTitleKurdish: "وزەی کارلێکەکان",
      lessonNumber: "5-2",
      lessonTitleKurdish: "هێزە کارلێک هاندەرەکان",
      pageStart: 142,
      pageEnd: 151,
      isConfidenceLow: false,
    },
    {
      id: "sec-unit-2-ch-6",
      unitNumber: 2,
      unitTitleKurdish: "کارلێککردنە کیمیاییەکان",
      chapterNumber: 6,
      chapterTitleKurdish: "خێرایی کارلێکەکان",
      lessonNumber: "6-1",
      lessonTitleKurdish: "کردەی کارلێک",
      pageStart: 152,
      pageEnd: 159,
      isConfidenceLow: false,
    },
    {
      id: "sec-unit-2-ch-6-l-2",
      unitNumber: 2,
      unitTitleKurdish: "کارلێککردنە کیمیاییەکان",
      chapterNumber: 6,
      chapterTitleKurdish: "خێرایی کارلێکەکان",
      lessonNumber: "6-2",
      lessonTitleKurdish: "خێرایی کارلێککردنی کیمیایی",
      pageStart: 160,
      pageEnd: 175,
      isConfidenceLow: false,
    },
    {
      id: "sec-unit-2-ch-7",
      unitNumber: 2,
      unitTitleKurdish: "کارلێککردنە کیمیاییەکان",
      chapterNumber: 7,
      chapterTitleKurdish: "هاوسەنگی کیمیایی",
      lessonNumber: "7-1",
      lessonTitleKurdish: "سروشتی هاوسەنگی کیمیایی",
      pageStart: 176,
      pageEnd: 185,
      isConfidenceLow: false,
    },
    {
      id: "sec-unit-2-ch-7-l-2",
      unitNumber: 2,
      unitTitleKurdish: "کارلێککردنە کیمیاییەکان",
      chapterNumber: 7,
      chapterTitleKurdish: "هاوسەنگی کیمیایی",
      lessonNumber: "7-2",
      lessonTitleKurdish: "لادانی هاوسەنگی",
      pageStart: 186,
      pageEnd: 192,
      isConfidenceLow: false,
    },
    {
      id: "sec-unit-2-ch-7-l-3",
      unitNumber: 2,
      unitTitleKurdish: "کارلێککردنە کیمیاییەکان",
      chapterNumber: 7,
      chapterTitleKurdish: "هاوسەنگی کیمیایی",
      lessonNumber: "7-3",
      lessonTitleKurdish: "هاوسەنگی لە گیراوەی ترش و تفت و خوێیەکاندا",
      pageStart: 193,
      pageEnd: 200,
      isConfidenceLow: false,
    },
    {
      id: "sec-unit-2-ch-7-l-4",
      unitNumber: 2,
      unitTitleKurdish: "کارلێککردنە کیمیاییەکان",
      chapterNumber: 7,
      chapterTitleKurdish: "هاوسەنگی کیمیایی",
      lessonNumber: "7-4",
      lessonTitleKurdish: "هاوسەنگی تواندنەوە",
      pageStart: 201,
      pageEnd: 213,
      isConfidenceLow: false,
    },
    {
      id: "sec-unit-2-ch-8",
      unitNumber: 2,
      unitTitleKurdish: "کارلێککردنە کیمیاییەکان",
      chapterNumber: 8,
      chapterTitleKurdish: "کارلێکەکانی ئۆکسان و لێککردنەوە",
      lessonNumber: "8-1",
      lessonTitleKurdish: "ئۆکسان و لێککردنەوە",
      pageStart: 214,
      pageEnd: 220,
      isConfidenceLow: false,
    },
    {
      id: "sec-unit-2-ch-8-l-2",
      unitNumber: 2,
      unitTitleKurdish: "کارلێککردنە کیمیاییەکان",
      chapterNumber: 8,
      chapterTitleKurdish: "کارلێکەکانی ئۆکسان و لێککردنەوە",
      lessonNumber: "8-2",
      lessonTitleKurdish: "هاوسەنگکردنی هاوکێشەکانی ئۆکسان - لێککردنەوە",
      pageStart: 221,
      pageEnd: 225,
      isConfidenceLow: false,
    },
    {
      id: "sec-unit-2-ch-8-l-3",
      unitNumber: 2,
      unitTitleKurdish: "کارلێککردنە کیمیاییەکان",
      chapterNumber: 8,
      chapterTitleKurdish: "کارلێکەکانی ئۆکسان و لێککردنەوە",
      lessonNumber: "8-3",
      lessonTitleKurdish: "هۆکارە ئۆکسێن و هۆکارە لێککەرەوەکان",
      pageStart: 226,
      pageEnd: 233,
      isConfidenceLow: false,
    },
    {
      id: "sec-unit-2-ch-9",
      unitNumber: 2,
      unitTitleKurdish: "کارلێککردنە کیمیاییەکان",
      chapterNumber: 9,
      chapterTitleKurdish: "کیمیای کارەبایی",
      lessonNumber: "9-1",
      lessonTitleKurdish: "گوزەرێک بۆ کیمیای کارەبایی",
      pageStart: 234,
      pageEnd: 237,
      isConfidenceLow: false,
    },
    {
      id: "sec-unit-2-ch-9-l-2",
      unitNumber: 2,
      unitTitleKurdish: "کارلێککردنە کیمیاییەکان",
      chapterNumber: 9,
      chapterTitleKurdish: "کیمیای کارەبایی",
      lessonNumber: "9-2",
      lessonTitleKurdish: "خانە ڤۆڵتاییەکان",
      pageStart: 238,
      pageEnd: 246,
      isConfidenceLow: false,
    },
    {
      id: "sec-unit-2-ch-9-l-3",
      unitNumber: 2,
      unitTitleKurdish: "کارلێککردنە کیمیاییەکان",
      chapterNumber: 9,
      chapterTitleKurdish: "کیمیای کارەبایی",
      lessonNumber: "9-3",
      lessonTitleKurdish: "خانە ئەلیکترۆلیتییەکان",
      pageStart: 247,
      pageEnd: 255,
      isConfidenceLow: false,
    },
    {
      id: "sec-unit-3-ch-10",
      unitNumber: 3,
      unitTitleKurdish: "کیمیای ئەندامی و ناوکی",
      chapterNumber: 10,
      chapterTitleKurdish: "کاربۆن و هایدرۆکاربۆنەکان",
      lessonNumber: "10-1",
      lessonTitleKurdish: "بوون و گرنگی کاربۆن",
      pageStart: 258,
      pageEnd: 262,
      isConfidenceLow: false,
    },
    {
      id: "sec-unit-3-ch-10-l-2",
      unitNumber: 3,
      unitTitleKurdish: "کیمیای ئەندامی و ناوکی",
      chapterNumber: 10,
      chapterTitleKurdish: "کاربۆن و هایدرۆکاربۆنەکان",
      lessonNumber: "10-2",
      lessonTitleKurdish: "ئاوێتە ئەندامییەکان",
      pageStart: 263,
      pageEnd: 267,
      isConfidenceLow: false,
    },
    {
      id: "sec-unit-3-ch-10-l-3",
      unitNumber: 3,
      unitTitleKurdish: "کیمیای ئەندامی و ناوکی",
      chapterNumber: 10,
      chapterTitleKurdish: "کاربۆن و هایدرۆکاربۆنەکان",
      lessonNumber: "10-3",
      lessonTitleKurdish: "هایدرۆکاربۆنە تێرەکان",
      pageStart: 268,
      pageEnd: 278,
      isConfidenceLow: false,
    },
    {
      id: "sec-unit-3-ch-10-l-4",
      unitNumber: 3,
      unitTitleKurdish: "کیمیای ئەندامی و ناوکی",
      chapterNumber: 10,
      chapterTitleKurdish: "کاربۆن و هایدرۆکاربۆنەکان",
      lessonNumber: "10-4",
      lessonTitleKurdish: "هایدرۆکاربۆنە ناتێرەکان",
      pageStart: 279,
      pageEnd: 293,
      isConfidenceLow: false,
    },
    {
      id: "sec-unit-3-ch-11",
      unitNumber: 3,
      unitTitleKurdish: "کیمیای ئەندامی و ناوکی",
      chapterNumber: 11,
      chapterTitleKurdish: "ئاوێتەی ئەندامی تر",
      lessonNumber: "11-1",
      lessonTitleKurdish: "کۆمەڵە فرمانییەکان (کاراکان) و پۆلەکانی ئاوێتە ئەندامییەکان",
      pageStart: 294,
      pageEnd: 303,
      isConfidenceLow: false,
    },
    {
      id: "sec-unit-3-ch-11-l-2",
      unitNumber: 3,
      unitTitleKurdish: "کیمیای ئەندامی و ناوکی",
      chapterNumber: 11,
      chapterTitleKurdish: "ئاوێتەی ئەندامی تر",
      lessonNumber: "11-2",
      lessonTitleKurdish: "پۆلی تری ئاوێتە ئەندامییەکان",
      pageStart: 304,
      pageEnd: 312,
      isConfidenceLow: false,
    },
    {
      id: "sec-unit-3-ch-11-l-3",
      unitNumber: 3,
      unitTitleKurdish: "کیمیای ئەندامی و ناوکی",
      chapterNumber: 11,
      chapterTitleKurdish: "ئاوێتەی ئەندامی تر",
      lessonNumber: "11-3",
      lessonTitleKurdish: "کارلێکە ئەندامییەکان",
      pageStart: 313,
      pageEnd: 315,
      isConfidenceLow: false,
    },
    {
      id: "sec-unit-3-ch-11-l-4",
      unitNumber: 3,
      unitTitleKurdish: "کیمیای ئەندامی و ناوکی",
      chapterNumber: 11,
      chapterTitleKurdish: "ئاوێتەی ئەندامی تر",
      lessonNumber: "11-4",
      lessonTitleKurdish: "پۆلیمەرەکان",
      pageStart: 316,
      pageEnd: 329,
      isConfidenceLow: false,
    },
    {
      id: "sec-unit-3-ch-12",
      unitNumber: 3,
      unitTitleKurdish: "کیمیای ئەندامی و ناوکی",
      chapterNumber: 12,
      chapterTitleKurdish: "کیمیای ناوکی",
      lessonNumber: "12-1",
      lessonTitleKurdish: "ناووك",
      pageStart: 330,
      pageEnd: 334,
      isConfidenceLow: false,
    },
    {
      id: "sec-unit-3-ch-12-l-2",
      unitNumber: 3,
      unitTitleKurdish: "کیمیای ئەندامی و ناوکی",
      chapterNumber: 12,
      chapterTitleKurdish: "کیمیای ناوکی",
      lessonNumber: "12-2",
      lessonTitleKurdish: "تیشکە لێکەهەڵوەشان",
      pageStart: 335,
      pageEnd: 342,
      isConfidenceLow: false,
    },
    {
      id: "sec-unit-3-ch-12-l-3",
      unitNumber: 3,
      unitTitleKurdish: "کیمیای ئەندامی و ناوکی",
      chapterNumber: 12,
      chapterTitleKurdish: "کیمیای ناوکی",
      lessonNumber: "12-3",
      lessonTitleKurdish: "ناووکە تیشکدانەوە",
      pageStart: 343,
      pageEnd: 346,
      isConfidenceLow: false,
    },
    {
      id: "sec-unit-3-ch-12-l-4",
      unitNumber: 3,
      unitTitleKurdish: "کیمیای ئەندامی و ناوکی",
      chapterNumber: 12,
      chapterTitleKurdish: "کیمیای ناوکی",
      lessonNumber: "12-4",
      lessonTitleKurdish: "ناووکە کەرتبوون و ناووکە یەکگرتن",
      pageStart: 347,
      pageEnd: 354,
      isConfidenceLow: false,
    },
  ],
};
